
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/helpdesk
        username: Diogo
        password: 197946
    jpa:
        show-sql: true
        hibernate:
            format_sql: true
            ddl-auto: update